package jp.kaleidot725.adbpad.resource

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006B5D)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF56FBE1)
val md_theme_light_onPrimaryContainer = Color(0xFF00201B)
val md_theme_light_secondary = Color(0xFF46645E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFC9E9E1)
val md_theme_light_onSecondaryContainer = Color(0xFF01201B)
val md_theme_light_tertiary = Color(0xFF3E627D)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFCAE6FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001E30)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFAFDFA)
val md_theme_light_onBackground = Color(0xFF191C1B)
val md_theme_light_surface = Color(0xFFFAFDFA)
val md_theme_light_onSurface = Color(0xFF191C1B)
val md_theme_light_surfaceVariant = Color(0xFFDAE5E1)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4946)
val md_theme_light_outline = Color(0xFF6F7976)
val md_theme_light_inverseSurface = Color(0xFF2D3130)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1EF)
val md_theme_light_inversePrimary = Color(0xFF29DEC5)

val md_theme_dark_primary = Color(0xFF29DEC5)
val md_theme_dark_onPrimary = Color(0xFF003730)
val md_theme_dark_primaryContainer = Color(0xFF005046)
val md_theme_dark_onPrimaryContainer = Color(0xFF56FBE1)
val md_theme_dark_secondary = Color(0xFFADCDC5)
val md_theme_dark_onSecondary = Color(0xFF183530)
val md_theme_dark_secondaryContainer = Color(0xFF2F4C46)
val md_theme_dark_onSecondaryContainer = Color(0xFFC9E9E1)
val md_theme_dark_tertiary = Color(0xFFA6CBEA)
val md_theme_dark_onTertiary = Color(0xFF08344C)
val md_theme_dark_tertiaryContainer = Color(0xFF254A64)
val md_theme_dark_onTertiaryContainer = Color(0xFFCAE6FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFB4AB)
val md_theme_dark_background = Color(0xFF191C1B)
val md_theme_dark_onBackground = Color(0xFFE0E3E1)
val md_theme_dark_surface = Color(0xFF191C1B)
val md_theme_dark_onSurface = Color(0xFFE0E3E1)
val md_theme_dark_surfaceVariant = Color(0xFF3F4946)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC9C5)
val md_theme_dark_outline = Color(0xFF899390)
val md_theme_dark_inverseSurface = Color(0xFFE0E3E1)
val md_theme_dark_inverseOnSurface = Color(0xFF2D3130)
val md_theme_dark_inversePrimary = Color(0xFF006B5D)
