package jp.kaleidot725.adbpad.domain.model

object Language {
    const val WINDOW_TITLE = "AdbPad(v0.1.0)"
    const val NOT_FOUND_DEVICE = "Not found device"
    const val NOT_FOUND_COMMAND = "Not found command"
    const val NOT_FOUND_INPUT_TEXT = "Not found input text"
    const val NOT_FOUND_SCREEN_SHOT = "Not found screenshot"
    const val EXECUTE = "Run"
    const val SAVE = "Save"
    const val DELETE = "Delete"
    const val SEND = "Send"
    const val TARGET_DEVICE = "Target Device"
    const val TOOL = "Tools"
    const val TAKE_SCREENSHOT = "Shoot"
    const val TAKE_THEME_SCREENSHOT = "Shoot(each Theme)"

    const val COMMAND_LAYOUT_BORDER_ON_TITLE = "レイアウト境界表示 ON"
    const val COMMAND_LAYOUT_BORDER_ON_DETAILS = "端末のUI要素のレイアウト境界表示をONにする"
    const val COMMAND_LAYOUT_BORDER_OFF_TITLE = "レイアウト境界表示 OFF"
    const val COMMAND_LAYOUT_BORDER_OFF_DETAILS = "端末のUI要素のレイアウト境界表示をOFFにする"
    const val COMMAND_TAP_EFFECT_ON_TITLE = "タップ表示 ON"
    const val COMMAND_TAP_EFFECT_ON_DETAILS = "端末の画面をタップした位置の表示をONにする"
    const val COMMAND_TAP_EFFECT_OFF_TITLE = "タップ表示 OFF"
    const val COMMAND_TAP_EFFECT_OFF_DETAILS = "端末の画面をタップした位置の表示をOFFにする"
    const val COMMAND_SLEEP_MODE_ON_TITLE = "スリープモードにしない ON"
    const val COMMAND_SLEEP_MODE_ON_DETAILS = "端末をスリープモードにしないようにする"
    const val COMMAND_SLEEP_MODE_OFF_TITLE = "スリープモードにしない OFF"
    const val COMMAND_SLEEP_MODE_OFF_DETAILS = "端末をスリープモードにするようにする"
    const val COMMAND_DARK_THEME_ON_TITLE = "ダークテーマON"
    const val COMMAND_DARK_THEME_ON_DETAILS = "端末のダークテーマ設定をONにします"
    const val COMMAND_DARK_THEME_OFF_TITLE = "ダークテーマOFF"
    const val COMMAND_DARK_THEME_OFF_DETAILS = "端末のダークテーマ設定をOFFにします"
    const val COMMAND_WIFI_ON_TITLE = "Wi-Fi ON"
    const val COMMAND_WIFI_ON_DETAILS = "端末のWi-Fi設定をONにします"
    const val COMMAND_WIFI_OFF_TITLE = "Wi-Fi OFF"
    const val COMMAND_WIFI_OFF_DETAILS = "端末のWi-Fi設定をOFFにします"
    const val COMMAND_DATA_ON_TITLE = "データ通信 ON"
    const val COMMAND_DATA_ON_DETAILS = "端末のデータ通信設定をONにします"
    const val COMMAND_DATA_OFF_TITLE = "データ通信 OFF"
    const val COMMAND_DATA_OFF_DETAILS = "端末のデータ通信設定をOFFにします"
    const val COMMAND_INPUT_TEXT_TITLE = "テキスト入力"
    const val COMMAND_INPUT_TEXT_DETAILS = "入力したテキストを端末に送信します"
    const val COMMAND_WIFI_AND_DATA_ON_TITLE = "Wi-Fi＆データ通信 ON"
    const val COMMAND_WIFI_AND_DATA_ON_DETAILS = "端末のWi-Fi設定とデータ通信設定の両方をONにします"
    const val COMMAND_WIFI_AND_DATA_OFF_TITLE = "Wi-Fi&データ通信 OFF"
    const val COMMAND_WIFI_AND_DATA_OFF_DETAILS = "端末のWi-Fi設定とデータ通信設定の両方をOFFにします"

    const val MENU_COMMAND_TITLE = "Command"
    const val MENU_INPUT_TEXT_TITLE = "Input Text"
    const val MENU_SCREENSHOT = "Screenshot"
}
