package jp.kaleidot725.adbpad.domain.model

object Language {
    const val WINDOW_TITLE = "AdbPad(v0.1.0)"
    const val NOT_FOUND_DEVICE = "デバイスがありません"
    const val NOT_FOUND_COMMAND = "コマンドがありません"
    const val NOT_FOUND_INPUT_TEXT = "入力テキストがありません"
    const val NOT_FOUND_SCREEN_SHOT = "スクリーンショットがありません"
    const val EXECUTE = "実行"
    const val SAVE = "保存"
    const val DELETE = "削除"
    const val SEND = "送信"
    const val TARGET_DEVICE = "ターゲット端末"
    const val TOOL = "ツール"
    const val TAKE_SCREENSHOT = "撮影する"
    const val TAKE_THEME_SCREENSHOT = "テーマ毎に撮影する"

    const val COMMAND_LAYOUT_BORDER_ON_TITLE = "レイアウト境界表示 ON"
    const val COMMAND_LAYOUT_BORDER_ON_DETAILS = "端末のUI要素のレイアウト境界表示をONにする"
    const val COMMAND_LAYOUT_BORDER_OFF_TITLE = "レイアウト境界表示 OFF"
    const val COMMAND_LAYOUT_BORDER_OFF_DETAILS = "端末のUI要素のレイアウト境界表示をOFFにする"
    const val COMMAND_TAP_EFFECT_ON_TITLE = "タップ表示 ON"
    const val COMMAND_TAP_EFFECT_ON_DETAILS = "端末の画面をタップした位置の表示をONにする"
    const val COMMAND_TAP_EFFECT_OFF_TITLE = "タップ表示 OFF"
    const val COMMAND_TAP_EFFECT_OFF_DETAILS = "端末の画面をタップした位置の表示をOFFにする"
    const val COMMAND_SLEEP_MODE_ON_TITLE = "スリープモードにしない ON"
    const val COMMAND_SLEEP_MODE_ON_DETAILS = "端末をスリープモードにしないようにする"
    const val COMMAND_SLEEP_MODE_OFF_TITLE = "スリープモードにしない OFF"
    const val COMMAND_SLEEP_MODE_OFF_DETAILS = "端末をスリープモードにするようにする"
    const val COMMAND_DARK_THEME_ON_TITLE = "ダークテーマON"
    const val COMMAND_DARK_THEME_ON_DETAILS = "端末のダークテーマ設定をONにします"
    const val COMMAND_DARK_THEME_OFF_TITLE = "ダークテーマOFF"
    const val COMMAND_DARK_THEME_OFF_DETAILS = "端末のダークテーマ設定をOFFにします"
    const val COMMAND_WIFI_ON_TITLE = "Wi-Fi ON"
    const val COMMAND_WIFI_ON_DETAILS = "端末のWi-Fi設定をONにします"
    const val COMMAND_WIFI_OFF_TITLE = "Wi-Fi OFF"
    const val COMMAND_WIFI_OFF_DETAILS = "端末のWi-Fi設定をOFFにします"
    const val COMMAND_DATA_ON_TITLE = "データ通信 ON"
    const val COMMAND_DATA_ON_DETAILS = "端末のデータ通信設定をONにします"
    const val COMMAND_DATA_OFF_TITLE = "データ通信 OFF"
    const val COMMAND_DATA_OFF_DETAILS = "端末のデータ通信設定をOFFにします"
    const val COMMAND_INPUT_TEXT_TITLE = "テキスト入力"
    const val COMMAND_INPUT_TEXT_DETAILS = "入力したテキストを端末に送信します"
    const val COMMAND_WIFI_AND_DATA_ON_TITLE = "Wi-Fi＆データ通信 ON"
    const val COMMAND_WIFI_AND_DATA_ON_DETAILS = "端末のWi-Fi設定とデータ通信設定の両方をONにします"
    const val COMMAND_WIFI_AND_DATA_OFF_TITLE = "Wi-Fi&データ通信 OFF"
    const val COMMAND_WIFI_AND_DATA_OFF_DETAILS = "端末のWi-Fi設定とデータ通信設定の両方をOFFにします"
}
